### PR TITLE
SpiffyTitles: Fix bad links

### PR DESCRIPTION
**Pull request by cottongin**
Some further refactoring likely needs to take place here; see something like [this from base Limnoria's Web implementation](https://github.com/progval/Limnoria/blob/master/plugins/Web/plugin.py#L112-L131)

### CODE REVIEW

**Comment by fred0r** [comment]
using this since a few days and. . . well . ..  it doesnt create any errors any everything works like before :D

**Comment by fred0r** [comment]
well .. . . it does create errors compared to the current version - testurl: 
https://www.bbc.com/news/world-europe-61327638

**Comment by fred0r** [comment]
thx - the bbc example-link now works again.
maybe you could also take a look into the announcement of msn links?
example url: https://www.msn.com/en-ca/entertainment/entertainmenttopstories/heard-takes-stand-accuses-depp-of-violent-sexual-assault/ar-AAWXiBH?li=AAggNb9

**Comment by fred0r** [comment]
https://www.reuters.com/article/us-health-coronavirus-romania-posters-idUSKBN22B1YV
works on orig but not with your variant.

**Comment by oddluck** [comment]
Sorry to ignore this for so long. Looks good but  I'm going to run some tests...

**Comment by fred0r** [comment]
if i remember correct this url worked with the initial pull request, but not with the default:
https://www.amazon.de/DenTek-Zahnseide-Sticks-Complete-Clean-St%C3%BCck/dp/B07JDM9G65

**Comment by fred0r** [comment]
this one also doesnt work:
https://nitter.net/latimes/status/1540356576862621699

**Pull request closed without merging**
